# Generated by Django 3.2.1 on 2021-05-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewproduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Phone', 'Phone'), ('CPU', 'CPU'), ('GPU', 'Graphics Card'), ('other', 'other')], max_length=100),
        ),
    ]
