# Generated by Django 3.2.1 on 2021-05-06 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewproduct', '0003_review_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
